Update .github/workflows/snyk-security.yml
Co-authored-by: sourcery-ai[bot] <58596630+sourcery-ai[bot]@users.noreply.github.com>
Signed-off-by: DAVID OKEAMAH  <whitneykiss741@gmail.com>

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -63,7 +63,8 @@ jobs:
         # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
         # Use || true to not fail the pipeline.
       - name: Snyk IaC test and report
-        run: snyk iac test --report # || true
+        run: |
+          snyk iac test --report || echo "Snyk IaC test failed, but continuing pipeline"
 
         # Build the docker image for testing
       - name: Build a Docker image
